# Generated by Django 4.2.1 on 2023-08-05 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('with_medicine_review', '0002_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_comment',
            name='review_board_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='with_medicine_review.review_board'),
        ),
    ]
