# Generated by Django 4.2.1 on 2023-08-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('with_medicine_free', '0002_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Free_Comment',
        ),
    ]
