# Generated by Django 4.2.1 on 2023-08-05 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('with_medicine_free', '0003_rename_comment_free_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_comment',
            name='free_board_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='with_medicine_free.free_board'),
        ),
    ]
